---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rubyzxyz/bms_backend
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize
